#Multi stage build

#Stage 1
FROM node:14-alpine as builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

#Stage 2
FROM node:14-alpine

RUN yarn global add serve

WORKDIR /app

COPY --from=builder /app/build .

EXPOSE 80

CMD ["serve", "-p", "80", "-s", "."]