version: '3'
services:
  react:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ./entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
     - .:/app
     - /app/node_modules/
    stdin_open: true